baseURL : "http://london.org/"
languageCode : en-us
title : Orbital
theme : orbital


params:
  social:
    facebook: test
    instagram: test
    twitter: test

  scripts:
    googleanalytics: 
    disqus: 
    
permalinks:
  posts: /:title/